### PR TITLE
expose credential preview attribute constructor

### PR DESCRIPTION
**Pull request by kukgini**
# Checklist

- [x] have run AriesFrameworkTests
- [x]  I have run AllTests

# Description

expose credential preview attribute constructor in public and set mime type as optional with default value (text/plain).

### CODE REVIEW

**Comment by conanoc** [comment]
Can you explain why this change is needed? Is the mime-type mandatory for other agents?

**Comment by kukgini** [comment]
I thought that it is mandatory in aca-py. but, let me check again.

**Comment by kukgini** [comment]
I was wrong. it is optional in issuing credential. it's weired because there was a reason i thought that. maybe it was fixed at some point. let me check again that it is ok in present proofs.

**Comment by kukgini** [comment]
With aca-py issuer, credential propose from AFSwift without mime-type can be failed. aca-py sends a credential offer message, but AFSwift fails to unwrap the connection from the messageContext.

**Comment by kukgini** [comment]
The original approach sets the mime type only when creating it in the dictionary. My approach allows to set the mime type in any situation. It seems that if the mime-type is not set anyway, decode issue occurs when receive credential offer message.

**Comment by kukgini** [comment]
Again it seems I am wrong. Even if the issuer provides credential-offer without mime-types, the problem does not occur at the framework level. I will close this PR.

**Pull request closed without merging**
