### PR TITLE
Fix proof request attribute bug.

### PR DESCRIPTION
**Pull request by kukgini**
# Checklist

- [x] have run AriesFrameworkTests
- [x] I have run AllTests

# Description

ProofAttributeInfo.names should be an array type. counter party can request proof request with names.

### CODE REVIEW

**Comment by kukgini** [comment]
@conanoc Could you look at why the test is failing?

**Comment by conanoc** [comment]
This may be an issue of macos runner version. I fixed it on #45. Merge with the main branch and then it will be fixed.

**Comment by kukgini** [comment]
I merged main branch into it and tests still fails.

**Comment by kukgini** [comment]
It's weird because tests have passed in my github repository before merge. but after merge, it fails in my repository too.

**Comment by conanoc** [comment]
Hmm.. strange. How about creating a new PR after closing this one?

**Pull request closed without merging**
