### PR TITLE
fix concurrency issues with replacing concurrent* to async*

### PR DESCRIPTION
**Pull request by kukgini**
# Checklist

- [x] have run AriesFrameworkTests
- [x] I have run AllTests

# Description

fix concurrency issues with replacing concurrent* to async*

# Related Issues

- #44

### CODE REVIEW

**Comment by conanoc** [comment]
It could fix the issue but I intended to use the concurrent version for efficiency. Can you create a test case that fails with the concurrent version? The test will also make sure that this change will fix that issue.

**Comment by kukgini** [comment]
@conanoc As you said, this solution sacrifices performance. However, I believe that improving performance through concurrency only makes sense if stability is achieved. 

Unfortunately I don't know how to write a test case that will always fail in unit tests. Moreover, this error only happens intermittently in my app, which I am experimenting with attached to the bcovrin testnet. AllTests that I do iteratively always succeed.

**Comment by conanoc** [comment]
The test doesn't have to fail always. It's enough to fail sometimes. I'll also look at this later.

**Comment by conanoc** [comment]
#50 has merged for this. Thanks for reporting the issue.

**Pull request closed without merging**
